### ISSUE TITLE
Admin user authentication fails

### ISSUE THREAD

**Issue by ggarrihy** [datacenter/ignite#1]
Using OVA

See attached image - looks like missing configuration step from inital setup

![ignitecorblock](https://cloud.githubusercontent.com/assets/6216895/9766358/5911f0ba-5710-11e5-9c00-5ca93e747126.jpg)

**Comment by vinayakbhakta** [comment]
The IP address given in the settings script and in the browser are different.

Browser -> 1.5.100.150
Script (see URL in the HTTP request) -> 10.0.1.16

They have to be the same.

Set the IP address in https://github.com/datacenter/ignite/blob/master/dist/scripts/utils/settings.6fc59791.js (line #21) and use the same in the browser.
