### ISSUE TITLE
Postgres DB permissions

### ISSUE THREAD

**Issue by jasonlunde** [datacenter/ignite#7]
I found that once the DB was created there were no access permissions to it. I had to manually set them for the postgres users. Also, I had to change the authentication mode for postgres from 'Peer' to 'MD5' in order for the setup script to run.

**Comment by fractlrao** [comment]
Please download OVA from https://cisco.box.com/s/rop1e3sg52tpwermvac5n7brxt04b7nk
Install or setup procedure for OVA is available in docs folder https://github.com/datacenter/ignite/blob/master/docs/ignite_ova_readme.md

**Comment by jasonlunde** [comment]
Works great...thank you.
